### ISSUE TITLE
Tasks for v1.0

### ISSUE THREAD

**Issue by jermspeaks** [jermspeaks/jermspeaks.github.io#1]
# Version 1.0 Milestones
- [x] Migration of About Me Page
- [x] Migration of old blog posts to new blog templates
- [x] Migration of Projects Page
- [ ] Transfer domain to this page
- [x] Create Jekyll Template #2

# Version 2.0 Milestones
- [ ] Create Page for Movie and Book Data (Quantified Self Page)

**Comment by jeremy-clearlabs** [comment]
Add:
- Robots.txt modifications for resume

Stretch goal:
- http://www.heropatterns.com/

**Comment by jermspeaks** [comment]
Done
